server:
  port: 8080

spring:
  application:
    name: download-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

file:
  upload:
    path: /path/